[package]
name = "logistics-management-go-rework"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3

[dependencies]
anyhow = "1.0.98"
async-graphql = { version = "7.0.17", features = ["uuid", "chrono", "decimal"] }
async-graphql-axum = "7.0.17"
axum = { version = "0.8.4", features = ["macros"] }
chrono = { version = "0.4.41", features = ["serde"] }
sea-orm = { version = "1.1.13", features = [
  "runtime-tokio-native-tls",
  "sqlx-postgres",
  "with-uuid",
  "with-chrono",
  "with-json",
] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sqlx = { version = "0.8.6", features = [
  "migrate",
  "postgres",
  "runtime-tokio-native-tls",
] }
tokio = { version = "1.46.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }
uuid = { version = "1.17.0", features = ["serde"] }
