name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      DOCKER_POSTGRES_USER: dummy
      DOCKER_POSTGRES_PASSWORD: dummy
      DOCKER_POSTGRES_DB: dummy
      DATABASE_URL: postgres://dummy:dummy@localhost:5432/dummy
      MAIL_HOST: localhost
      MAIL_PORT: "1025"
      MAIL_SECURE: "false"
      MAIL_FROM_ADDRESS: dummy@example.com
      DOCKER_MINIO_ROOT_USER: minioadmin
      DOCKER_MINIO_ROOT_PASSWORD: minioadmin
      DOCKER_MINIO_BUCKET: staging-bucket
      DOCKER_MINIO_ENDPOINT: http://localhost:9000
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Start Docker services
        run: docker compose -f compose.dev.yaml up -d

      - name: Lint with Biome
        run: bun run lint

      - name: Wait for services to be ready
        run: sleep 5

      - name: Run tests
        run: bun test --preload ./packages/graphql/tests/setup.ts

      - name: Build project
        run: bun turbo build
